#!/usr/bin/env bash
# update-package-managers.sh — Generate Homebrew formula + Scoop manifest and
# open pull requests for review after a release.
#
# Usage:
#   ./scripts/update-package-managers.sh           # auto-detects latest version from S3
#   ./scripts/update-package-managers.sh 1.0.8     # explicit version override
#
# Prerequisites:
#   - curl
#   - git with push access to the target repos via SSH
#   - gh (GitHub CLI) — authenticated with `gh auth login`

set -euo pipefail

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
BASE_URL="https://razorpay.com/cli"
HOMEBREW_REPO="git@github.com:razorpay/homebrew-razorpay-cli.git"
SCOOP_REPO="git@github.com:razorpay/scoop-razorpay-cli.git"

# ---------------------------------------------------------------------------
# Resolve version — auto-detect from S3 or accept as argument
# ---------------------------------------------------------------------------
if [[ $# -ge 1 ]]; then
  VERSION="$1"
else
  echo "==> Auto-detecting latest version from ${BASE_URL}/latest..."
  VERSION=$(curl -fsSL "${BASE_URL}/latest")
fi

VERSION_NUM="${VERSION#v}"  # strip leading v if present

if [[ -z "${VERSION_NUM}" ]]; then
  echo "ERROR: Could not determine version. Pass it manually: $0 <version>"
  exit 1
fi

echo "==> Updating package managers for version ${VERSION_NUM}"

# ---------------------------------------------------------------------------
# Download checksums
# ---------------------------------------------------------------------------
TMPDIR=$(mktemp -d)
trap 'rm -rf "${TMPDIR}"' EXIT

echo "==> Downloading checksums..."
curl -fsSL "${BASE_URL}/latest/razorpay-mac-checksums.txt" -o "${TMPDIR}/mac-checksums.txt"
curl -fsSL "${BASE_URL}/latest/razorpay-windows-checksums.txt" -o "${TMPDIR}/windows-checksums.txt"

# ---------------------------------------------------------------------------
# Extract SHA256 hashes
# ---------------------------------------------------------------------------
get_sha() {
  local file="$1" checksums="$2"
  grep "${file}" "${checksums}" | awk '{print $1}'
}

MAC_ARM64_SHA=$(get_sha "mac-os_arm64.tar.gz" "${TMPDIR}/mac-checksums.txt")
MAC_AMD64_SHA=$(get_sha "mac-os_x86_64.tar.gz" "${TMPDIR}/mac-checksums.txt")
WIN_AMD64_SHA=$(get_sha "windows_x86_64.zip" "${TMPDIR}/windows-checksums.txt")
WIN_I386_SHA=$(get_sha "windows_i386.zip" "${TMPDIR}/windows-checksums.txt")

echo "  mac arm64:     ${MAC_ARM64_SHA}"
echo "  mac x86_64:    ${MAC_AMD64_SHA}"
echo "  win x86_64:    ${WIN_AMD64_SHA}"
echo "  win i386:      ${WIN_I386_SHA}"

# ---------------------------------------------------------------------------
# Generate Homebrew formula
# ---------------------------------------------------------------------------
echo "==> Generating Homebrew formula..."

FORMULA_DIR="${TMPDIR}/homebrew"
mkdir -p "${FORMULA_DIR}"

cat > "${FORMULA_DIR}/razorpay.rb" <<RUBY
# typed: false
# frozen_string_literal: true

# This file was generated by scripts/update-package-managers.sh. Do not edit manually.
class Razorpay < Formula
  desc "Official Razorpay CLI."
  homepage "https://github.com/razorpay/razorpay-cli"
  version "${VERSION_NUM}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "${BASE_URL}/latest/razorpay_mac-os_arm64.tar.gz"
      sha256 "${MAC_ARM64_SHA}"
    else
      url "${BASE_URL}/latest/razorpay_mac-os_x86_64.tar.gz"
      sha256 "${MAC_AMD64_SHA}"
    end
  end

  def install
    bin.install "razorpay"
  end

  def caveats
    <<~EOS
      Thanks for installing the Razorpay CLI! If this is your first time using the CLI, be sure to run \`razorpay configure\` first.
    EOS
  end

  test do
    assert_match "razorpay version", shell_output("#{bin}/razorpay --version")
  end
end
RUBY

echo "  Formula written to ${FORMULA_DIR}/razorpay.rb"

# ---------------------------------------------------------------------------
# Generate Scoop manifest
# ---------------------------------------------------------------------------
echo "==> Generating Scoop manifest..."

SCOOP_DIR="${TMPDIR}/scoop"
mkdir -p "${SCOOP_DIR}"

cat > "${SCOOP_DIR}/razorpay.json" <<JSON
{
  "version": "${VERSION_NUM}",
  "description": "Official Razorpay CLI.",
  "homepage": "https://github.com/razorpay/razorpay-cli",
  "license": "MIT",
  "architecture": {
    "64bit": {
      "url": "${BASE_URL}/latest/razorpay_windows_x86_64.zip",
      "hash": "${WIN_AMD64_SHA}"
    },
    "32bit": {
      "url": "${BASE_URL}/latest/razorpay_windows_i386.zip",
      "hash": "${WIN_I386_SHA}"
    }
  },
  "bin": "razorpay.exe",
  "checkver": {
    "url": "${BASE_URL}/latest",
    "regex": "v([\\\\d.]+)"
  },
  "autoupdate": {
    "architecture": {
      "64bit": {
        "url": "${BASE_URL}/latest/razorpay_windows_x86_64.zip"
      },
      "32bit": {
        "url": "${BASE_URL}/latest/razorpay_windows_i386.zip"
      }
    }
  }
}
JSON

echo "  Manifest written to ${SCOOP_DIR}/razorpay.json"

# ---------------------------------------------------------------------------
# Create PR for Homebrew formula
# ---------------------------------------------------------------------------
echo "==> Creating PR for Homebrew formula in ${HOMEBREW_REPO}..."

BREW_CLONE="${TMPDIR}/homebrew-razorpay-cli"
git clone "${HOMEBREW_REPO}" "${BREW_CLONE}" 2>/dev/null || {
  echo "ERROR: Could not clone ${HOMEBREW_REPO}. Make sure the repo exists and you have access."
  exit 1
}

BRANCH_NAME="update/v${VERSION_NUM}"
HOMEBREW_PR_URL=""
SCOOP_PR_URL=""

cd "${BREW_CLONE}"
# Switch to the branch — reuse it if it already exists on the remote
if git ls-remote --exit-code --heads origin "${BRANCH_NAME}" >/dev/null 2>&1; then
  git fetch origin "${BRANCH_NAME}"
  git checkout "${BRANCH_NAME}"
else
  git checkout -b "${BRANCH_NAME}"
fi

# Copy the generated formula after switching branches to avoid checkout conflicts
cp "${FORMULA_DIR}/razorpay.rb" "${BREW_CLONE}/razorpay.rb"
git add razorpay.rb
if git diff --cached --quiet; then
  echo "  No changes to Homebrew formula — skipping."
else
  git commit -m "Update razorpay formula to v${VERSION_NUM}"
  git push -u origin "${BRANCH_NAME}"
  # Open a PR (skip if one already exists for this branch)
  if HOMEBREW_PR_URL=$(gh pr view "${BRANCH_NAME}" --repo razorpay/homebrew-razorpay-cli --json url --jq '.url' 2>/dev/null); then
    echo "  PR already exists — updated branch pushed."
  else
    HOMEBREW_PR_URL=$(gh pr create \
      --repo razorpay/homebrew-razorpay-cli \
      --head "${BRANCH_NAME}" \
      --title "Update razorpay formula to v${VERSION_NUM}" \
      --body "Auto-generated by \`scripts/update-package-managers.sh\`. Updates the Homebrew formula to v${VERSION_NUM}.")
  fi
  echo "  Homebrew PR: ${HOMEBREW_PR_URL}"
fi

# ---------------------------------------------------------------------------
# Create PR for Scoop manifest
# ---------------------------------------------------------------------------
echo "==> Creating PR for Scoop manifest in ${SCOOP_REPO}..."

SCOOP_CLONE="${TMPDIR}/scoop-razorpay-cli"
git clone "${SCOOP_REPO}" "${SCOOP_CLONE}" 2>/dev/null || {
  echo "ERROR: Could not clone ${SCOOP_REPO}. Make sure the repo exists and you have access."
  exit 1
}

cd "${SCOOP_CLONE}"
# Switch to the branch — reuse it if it already exists on the remote
if git ls-remote --exit-code --heads origin "${BRANCH_NAME}" >/dev/null 2>&1; then
  git fetch origin "${BRANCH_NAME}"
  git checkout "${BRANCH_NAME}"
else
  git checkout -b "${BRANCH_NAME}"
fi

# Copy the generated manifest after switching branches to avoid checkout conflicts
cp "${SCOOP_DIR}/razorpay.json" "${SCOOP_CLONE}/razorpay.json"
git add razorpay.json
if git diff --cached --quiet; then
  echo "  No changes to Scoop manifest — skipping."
else
  git commit -m "Update razorpay manifest to v${VERSION_NUM}"
  git push -u origin "${BRANCH_NAME}"
  # Open a PR (skip if one already exists for this branch)
  if SCOOP_PR_URL=$(gh pr view "${BRANCH_NAME}" --repo razorpay/scoop-razorpay-cli --json url --jq '.url' 2>/dev/null); then
    echo "  PR already exists — updated branch pushed."
  else
    SCOOP_PR_URL=$(gh pr create \
      --repo razorpay/scoop-razorpay-cli \
      --head "${BRANCH_NAME}" \
      --title "Update razorpay manifest to v${VERSION_NUM}" \
      --body "Auto-generated by \`scripts/update-package-managers.sh\`. Updates the Scoop manifest to v${VERSION_NUM}.")
  fi
  echo "  Scoop PR: ${SCOOP_PR_URL}"
fi

# ---------------------------------------------------------------------------
echo ""
echo "Done! Review and merge the PRs to publish v${VERSION_NUM}."
echo ""
if [[ -n "${HOMEBREW_PR_URL}" ]]; then
  echo "  Homebrew PR: ${HOMEBREW_PR_URL}"
fi
if [[ -n "${SCOOP_PR_URL}" ]]; then
  echo "  Scoop PR:    ${SCOOP_PR_URL}"
fi
echo ""
echo "Once merged, users can install via:"
echo "  brew install razorpay/razorpay-cli/razorpay    (macOS)"
echo "  scoop bucket add razorpay https://github.com/razorpay/scoop-razorpay-cli && scoop install razorpay   (Windows)"
